TODO_list/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls", namespace="todo")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo/urls.py
from django.urls import path

from todo.views import TagListView, TagCreateView, TagUpdateView, TagDeleteView, TaskListView, TaskCreateView, \
    TaskUpdateView, TaskDeleteView, task_status

urlpatterns = [
    path(
        "",
        TaskListView.as_view(),
        name="task-list"
    ),
    path(
        "tasks/create/",
        TaskCreateView.as_view(),
        name="task-create"
    ),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "tasks/<int:pk>/status/",
        task_status,
        name="task-status"
    ),
    path(
        "tags/",
        TagListView.as_view(),
        name="tag-list"
    ),
    path(
        "tags/create/",
        TagCreateView.as_view(),
        name="tag-create"
    ),
    path(
        "tags/<int:pk>/update/",
        TagUpdateView.as_view(),
        name="tag-update"
    ),
    path(
        "tags/<int:pk>/delete/",
        TagDeleteView.as_view(),
        name="tag-delete"
    ),
]

app_name = "todo"

todo/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.CharField(max_length=65)
    datetime = models.DateTimeField(auto_now=True)
    deadline = models.DateTimeField(null=True, blank=True)
    work_status = models.BooleanField()
    tags = models.ManyToManyField(Tag, related_name="tasks")

    def __str__(self):
        return f"{self.content} (created: {self.datetime})"

todo/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.views import generic

from todo.models import Tag, Task


class TagListView(generic.ListView):
    model = Tag
    paginate_by = 5


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo:tag-list")


class TaskListView(generic.ListView):
    model = Task
    paginate_by = 3


class TaskCreateView(generic.CreateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todo:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todo:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    template_name = "todo/task_confirm_delete.html"
    success_url = reverse_lazy("todo:task-list")


def task_status(request, pk: int) -> HttpResponseRedirect:
    task = Task.objects.get(id=pk)
    if task.work_status:
        task.work_status = False
    if not task.work_status:
        task.work_status = True
    task.save()
    return HttpResponseRedirect(reverse("todo:task-list"))

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>TODO list</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}

            {% block pagination %}
                {% include "includes/pagination.html" %}
            {% endblock %}

        </div>
    </div>
</div>
</body>

</html>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'todo:task-list' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'todo:tag-list' %}">Tag</a></li>
</ul>

templates/todo/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Tag?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Delete" class="btn btn-danger">
    <a href="/tags/" role="button" class="btn btn-primary">Cancel</a>
  </form>
{% endblock %}

templates/todo/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Tag List</h1>
  {% if tag_list %}
  <table class="table table-hover">
    <tr>
      <th>Name</th>
      <th>Update</th>
      <th>Delete</th>
    </tr>
  {% for tag in tag_list %}
    <tr>
      <td>{{ tag.name }}</td>
      <td>
        <a href="{% url 'todo:tag-update' pk=tag.id%} " class="btn btn-primary">Update</a>
      </td>
      <td>
        <a href="{% url 'todo:tag-delete' pk=tag.id%} " class="btn btn-danger">Delete</a>
      </td>
    </tr>
  {% endfor %}
  {% else %}
      <p>There are no tags in the list.</p>
  </table>
{% endif %}
  <a href="{% url 'todo:tag-create' %}" class="btn btn-primary">
    Create
  </a>
{% endblock %}

templates/todo/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Task?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Delete" class="btn btn-danger">
    <a href="/tasks/" role="button" class="btn btn-primary">Cancel</a>
  </form>
{% endblock %}

templates/todo/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo/task_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
  TODO List

  <a href="{% url 'todo:task-create' %}" class="btn btn-primary float-lg-right">Add Task</a>
</h1>
<br>
{% for task in task_list %}
  <hr>
  <p>
    <h3><strong>{{ task.content }}</strong></h3>
    {% if task.work_status %}
      <p class="text-secondary">Done</p>
      <a href="{%  url 'todo:task-status' pk=task.id %}" class="btn btn-secondary float-right">
        Undo
      </a>
    {% else %}
      <p class="text-danger">Not Done</p>
      <a href="{% url 'todo:task-status' pk=task.id %}" class="btn btn-success float-right">
        Complete
      </a>
    {% endif %}
  </p>

  <p>Created: {{ task.datetime }}</p>
  <p>Tags:
    {% for tag in task.tags.all %}
      {{ tag.name }}
    {% endfor %}
    <a href="{% url 'todo:task-update' pk=task.id %}">Update</a>
    <a href="{% url 'todo:task-delete' pk=task.id %}">Delete</a>
  </p>
{% endfor %}
{% endblock %}